name: Sagemaker Operator Image

on:
  release:
    types: [created]

env:
  IMG: farrd/amazon-sagemaker-operator-for-k8s:${{ env.GITHUB_REF }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: aws/amazon-sagemaker-operator-for-k8s
        ref: ${{ env.GITHUB_REF }}
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build
      run: make docker-build
    - name: Push
      run: make docker-push
