name: Sagemaker Operator Images

on: push

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: aws/amazon-sagemaker-operator-for-k8s
    - name: Build
      run: make docker-build
      env:
        IMG: dfarr/amazon-sagemaker-operator-for-k8s:latest
    - name: Push
      run: make docker-push
      env:
        TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
