name: Sagemaker Operator Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - id: extract_tag
      name: Extract tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: aws/amazon-sagemaker-operator-for-k8s
        ref: ${{ steps.extract_tag.outputs.TAG }}
    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build
      run: make docker-build
      env:
        IMG: farrd/amazon-sagemaker-operator-for-k8s:${{ steps.extract_tag.outputs.TAG }}
    - name: Push
      run: make docker-push
      env:
        IMG: farrd/amazon-sagemaker-operator-for-k8s:${{ steps.extract_tag.outputs.TAG }}
