name: Build and Push Sagemaker Docker Image

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Clone aws/amazon-sagemaker-operator-for-k8s
      uses: actions/checkout@v2
      with:
        repository: aws/amazon-sagemaker-operator-for-k8s
